DAY_CHOICE_BUTTON = "Обрати день"
TODAY_SCHEDULE_BUTTON = "Розклад сьогодні"
WEEK_SCHEDULE_BUTTON = "Розклад на тиждень"
BACK_BUTTON = "\U00002B05 Back"

# WEEKDAYS
MONDAY_BUTTON = "Понеділок"
TUESDAY_BUTTON = "Вівторок"
WEDNESDAY_BUTTON = "Середа"
THURSDAY_BUTTON = "Четвер"
FRIDAY_BUTTON = "П'ятниця"
WEEKDAYS = [MONDAY_BUTTON, TUESDAY_BUTTON, WEDNESDAY_BUTTON, THURSDAY_BUTTON, FRIDAY_BUTTON]

# OPERATIONS
ADD_LESSON_BUTTON = "Додати"
DELETE_LESSON_BUTTON = "Видалити"
EDIT_LESSON_BUTTON = "Редагувати"

# DEFAULT VALUES
NO_LESSON = "  " + " \u002D " * 5